# --- EdgeSimGym (QMIX) hyperparameters ---
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 1000000

runner: "episode"

buffer_size: 5000
batch_size: 128

target_update_interval: 200

agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

lr: 0.0003
critic_lr: 0.0003

name: "edge_qmix"

